### ISSUE TITLE
trailingComma potentially harmful on IE11

### ISSUE THREAD

**Issue by proxi** [Doist/prettier-config#14]
CC @Doist/frontend @Doist/integrations @Doist/back-end 

We format with `trailingComma: "always"` option. When we agreed on it, I [brought up some concerns](https://github.com/Doist/prettier-config/pull/5#issuecomment-637029783) that were dismissed, but now that we are adopting formatting in more places, I'd like to discuss this in more depth.

The issue is that trailing commas in function parameters do not work in IE11, Android Webview and possible some other old browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Browser_compatibility This is the reason default in prettier is 'es5'.

I'm concerned that if we applied formatting to some of the repositories that do not transpile code (or perhaps inline JavaScript in html files?) things will break unpredictably. It seems very difficult to predict and/or prevent. I'd like to hear team's opinion on this (especially if you know of non-transpiled JS in your repos).

**Comment by rfgamaral** [comment]
I've always used `es5` in my personal projects and previous company projects and never had a use case where `all` would be helpful. But then again, I don't have the necessary context from older discussions related to Doist's projects so this is just my biased and personal opinion.

**Comment by proxi** [comment]
@rfgamaral Please see https://github.com/Doist/prettier-config/pull/5

**Comment by rfgamaral** [comment]
I've seen it, I just want more context on the questions you raised in this issue ;)

**Comment by gnapse** [comment]
Do we have a specific issue due to this right now? We're hopefully on our way out of the IE11 support train, so it shouldn't be an issue for too long. Also, can't this be something that is stripped off our code at build time?

That being said, I'm not opposed to dial this back if needed.

**Comment by henningmu** [comment]
What Ernesto said. IE11 will slowly be phased out, there's no issue as all our code goes through a compilation step that removes these commas anyway. I don't think we need to solve a problem we don't have right now.

However, thank you for bringing it up. Certainly good to keep in the back of ones head in case we run into such an issue in the future ;)

A final note on:

> I'm concerned that if we applied formatting to some of the repositories that do not transpile code

If we really were to do that I think it's sensible to override this setting in that specific repository. I'd argue the majority of consumers of this config do have a build toolchain in place anyway and can take care of this if necessary.

**Comment by proxi** [comment]
> If we really were to do that I think it's sensible to override this setting in that specific repository.

My only concern is that it is difficult to say which files are not transpiled and run in browser context.

I created first of PRs in Twist backend to investigate potential impact: https://github.com/Doist/Twist/pull/901 In this case, it seems that all the files are transpiled, so it's not an issue.

**Comment by proxi** [comment]
@Doist/frontend @Doist/integrations @Doist/back-end All teams please: if you know of any instances where we deploy untranspiled JS code, please list it here.

**Comment by proxi** [comment]
Closing this: I have now mostly fixed formatting in twist and todoist repositories. There's a lot of untranspiled code in there and we excluded it from formatting.
