### ISSUE TITLE
About how to better load this in other projects

### ISSUE THREAD

**Issue by gnapse** [Doist/prettier-config#4]
Janusz brought up an issue about unifying how this config is incorporated into projects. I personally do not have a strong feeling that we should go this far as to control this on each and every project. But after our initial conversation we thought to bring it up here.

We tend to privilege having separate config files for packages (that is, having a `jest.config.js`, `lint-staged.config.js`, etc. instead of adding these configs as json inside `package.json`). This unclutters the `package.json` and makes it easier to find these configs. Also, having them be `.js` files could allow some dynamic customization advantages.

However, having sad that, this prettier config in particular is currently a one-liner in the projects where it is being used. And presumably our policy is to not make it a habit to customize it in our own projects (as opposed to jest, lint-staged and other configs that are harder to make it consistent and unique for all projects, hence each project will have their own).

So the question is: do we want to enforce this? If so, and we go the external-file-config approach, do we want to force it for prettier too, or maybe we see it ok as an exception and let it be a one-liner inside `package.json`?

**Comment by henningmu** [comment]
I'm okay with either. Though I believe if it's more than a one-liner it should be in a separate config file instead of inside `package.json`. 

One could argue that, for consistency's sake, we should then always put it in a separate file. However, I think prettier should never be customised in a project so we can make the exception here and keep it inside `package.json` 👍

**Comment by proxi** [comment]
Henning makes a good point - it seems like it is never intended to override prettier. So I'm for making an exception in this case and keeping it in package.json (I agree that separate file is better in general).

**Comment by dmiotti** [comment]
Agree, I got the same concern when creating `eslint-config` and I guess that‘s fine having different ways to load configurations as long as they are centralized, in a git repo at best 👍🏻

**Comment by proxi** [comment]
Let's keep this as one-liner in package.json as currently documented - it's not intended to ever be overriden. For other similar packages, we will also document how to integrate them, listing override options if necessary.
